### ISSUE TITLE
配置运行报错

### ISSUE THREAD

**Issue by zhuoyue03007** [oncemi/OnceMi.AspNetCore.OSS#14]
.net6   用此配置方式配置 运行会报错  services.AddOSSService("aliyunoss", "OSSProvider");
项目JSON配置文件节点存在并正确配置
![image](https://user-images.githubusercontent.com/24694226/159143251-eebcd99e-cffa-424b-a724-a15c6559a612.png)

**Comment by withsalt** [comment]
麻烦贴一下详细的代码，包括配置文件和program中的。

**Comment by staoran** [comment]
这里确实有问题，我也遇到同样的问题。最终我不得不用 `AddOSSService(this IServiceCollection services, string name, Action<OSSOptions> option)`添加服务。
```
services.AddOSSService("Default", "OSSProvider:Default");
services.AddOSSService("HY", "OSSProvider:HY");
```
这个方法，在某些情况下会引发异常，导致程序无法启动。
具体报错为：
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ConfigurationManager'.
   at Microsoft.Extensions.Configuration.ReferenceCountedProviderManager.AddProvider(IConfigurationProvider provider)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.<>c__DisplayClass25_0.b__2(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at System.Serve.Run(RunOptions options, String urls)
   at Program.
$(String[] args) in D:\OneDrive\GIT\XXX\XXX.Web.Entry\Program.cs:line 1
```
奇怪的是，在我开发环境（Windows 10）可以正常运行。在开发环境的 Docker（Linux containers） 中，也能正常运行。在服务器（CentOS 8.5.2111 x86_64）的 Docker 中，报上面的错误。

**Comment by withsalt** [comment]
好的，我排查一下。

**Comment by withsalt** [comment]
fixed.
